; ==========================================================
; CONFIGURACIÓN GLOBAL (Compartida por todos los entornos)
; ==========================================================
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    esphome/AsyncTCP-esphome @ ^2.0.0
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0
; ==========================================================
; ENTORNO 1: SUBIDA POR CABLE USB (Respaldo / Serial)
; ==========================================================
[env:cable_usb]
upload_protocol = esptool
; Opcional: Si tienes varios puertos, puedes forzar el COM aquí
; upload_port = COM3 
; ==========================================================
; ENTORNO 2: SUBIDA INALÁMBRICA (OTA Principal)
; ==========================================================
[env:wifi_ota]
upload_protocol = espota
; Aquí pones la IP estática de tu ESP32 o su hostname
upload_port = 192.168.4.1
; upload_port = ESP32_Potencia.local